Fix url field missing in generated client
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_nanny/plugins.py", line 524, in _register_device
    "msg": f"Success! Device can now be managed remotely: {device.url}"
AttributeError: 'OctoPrintDeviceKey' object has no attribute 'url'